### ISSUE TITLE
Docker build: Error at step 21 of 24

### ISSUE THREAD

**Issue by hamdanyc** [ashbaldry/designer#83]
Step 21/24 : RUN R -e 'remotes::install_local(upgrade = "never")'
 ---> Running in 3d53a55fd6ec
at step 21 I have this error:
Error: Failed to install 'unknown package' from local:
  cannot open the connection
In addition: Warning messages:
1: In read.dcf(path) :
  cannot open compressed file '/build_zone/DESCRIPTION', probable reason 'No such file or directory'
2: In read.dcf(path) :
  cannot open compressed file '/build_zone/DESCRIPTION', probable reason 'No such file or directory'
Execution halted
The command '/bin/sh -c R -e 'remotes::install_local(upgrade = "never")'' returned a non-zero code: 1

How can I overcome it, Thanks.

**Comment by ashbaldry** [comment]
Hello, it looks like the error is coming because the docker command is not running in the same directory as the package code. If you change the directory to the designer repository it should work.

Alternatively, I have managed to host the latest version on docker hub, running `docker pull ashbaldry/designer` should also work.

**Comment by hamdanyc** [comment]
Will try and thanks.
